---
- name: Change address of node-exporter on host
  replace:
    path: "{{ docker_compose_yml_path }}prometheus/prometheus.yml"
    regexp: '(\b[0-9]{1,3}\.){3}[0-9]{1,3}\b'
    replace: '{{ ansible_docker0.ipv4.address }}'
    backup: no
- name: Destroy docker-compose
  community.docker.docker_compose:
    project_src: "{{ docker_compose_yml_path }}"
    state: absent
- name: Deploy docker-compose
  community.docker.docker_compose:
    project_src: "{{ docker_compose_yml_path }}"
    state: present