---
- name: Destroy docker-compose
  community.docker.docker_compose:
    project_src: "{{ docker_compose_yml_path }}"
    state: absent
- name: Deploy docker-compose
  community.docker.docker_compose:
    project_src: "{{ docker_compose_yml_path }}"
    state: present